---

- hosts: localhost
  become: true
  tasks:


# pip

  - name: install pip
    apt: 
      name: python3-pip

  - name: install matplotlib
    pip:
      name: numpy, matplotlib


# basic packages

  - name: install basic packages
    apt:
      name: git, neovim, htop, 


# cycletest

  - name: install cycletest dependencies
    apt:
      name: build-essential, libnuma-dev

  - name: clone cycletest repo
    ansible.builtin.git:
      repo: git://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git
      dest: /src/rt-tests
      clone: yes

  - name: cycletest make all
    ansible.builtin.command: 
      cmd: make all
      chdir: /src/rt-tests

  - name: cycletest make install
    ansible.builtin.command: 
      cmd: make install
      chdir: /src/rt-tests
