---

- hosts: localhost
  tasks:


# pip

  - name: install basic packages
    become: true
    apt: 
      name: python3, python3-pip, git

  - name: install matplotlib
    become: true
    pip:
      name: numpy, matplotlib

# cycletest

  - name: install cycletest dependencies
    apt:
      name: build-essential, libnuma-dev

  - name: clone cycletest repo
    ansible.builtin.git:
      repo: git://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git
      dest: "{{ ansible_env.HOME }}/src/rt-tests"
      clone: yes

  - name: cycletest make all
    become: true
    ansible.builtin.command: 
      cmd: make all
      chdir: "{{ ansible_env.HOME }}/src/rt-tests"

  - name: cycletest make install
    become: true
    ansible.builtin.command: 
      cmd: make install
      chdir: "{{ ansible_env.HOME }}/src/rt-tests"
